### ISSUE TITLE
Awesome Crate. Need help in using it as a wasm pkg. An example code will help.

### ISSUE THREAD

**Issue by manishekhawat** [ndarilek/tts-rs#1]
Hi @ndarilek,
 
Good to see this crate. Awesome work there. I am trying to integrate this crate to my web app using wasm. I am passing the text caught through the speech recognition API of browser, want to send this text to TTS to process and speak the text. Just an experimental approach. 

FYI - I am new to Rust lang and WASM. Thus, an example code of how to use it with WASM (using wasm-bindgen) will be of great help, thank you.

Regards
MS

**Comment by ndarilek** [comment]
I haven't actually tried the wasm support, so don't know what to tell 
you. I'd originally planned on using it in a context where I later 
learned I couldn't link in native modules, so instead I made a 
best-effort attempt to get it compiling.


I'd imagine that the example in examples/hello_world.rs should compile 
under wasm-bindgen, cargo-web, or whatever tooling folks use. Maybe you 
could give one of those a shot and report back with your findings?

**Comment by ndarilek** [comment]
With cargo-make installed:

```bash
$ cargo make run-web-example
```

spins up a simple example running on port 8080. Type text to speak into a form, and set its rate/pitch/volume.
