### ISSUE TITLE
speech-dispatcher-rs writes to null pointer if speech-dispatcher fails to start

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [ndarilek/tts-rs#13]
Copied from https://gitlab.com/ndarilek/speech-dispatcher-rs/-/issues/1

---

`spd_open` and `spd_open2` both return null on error<sup>1</sup> instead of a valid pointer, but this library doesn't check for that and immediately writes to the pointer:

* https://gitlab.com/ndarilek/speech-dispatcher-rs/-/blob/006a4835be6372fb0326af5f0502d59188ab0254/speech-dispatcher/src/lib.rs#L159-165
* https://gitlab.com/ndarilek/speech-dispatcher-rs/-/blob/006a4835be6372fb0326af5f0502d59188ab0254/speech-dispatcher/src/lib.rs#L186-195

This does happen in practice; I added an explicit panic on null there and eventually managed to trigger it by repeatedly re-running a basic program. I'd previously been seeing rare segmentation faults. (I have no idea *why* speech-dispatcher failed to work, but it did.)

Those methods should probably return some form of `Result<Self, Error>`.

1: See [spd-say](https://github.com/brailcom/speechd/blob/1a9fc70f8666643883e5383ef0efb4682464f0f6/src/clients/say/say.c#L110-L113) code or speech-dispatcher's code

---

More recently I no longer have access to a working Linux system. But my Windows system has Ubuntu via WSL2 with a broken audio configuration, so speech-dispatcher *always* fails, leading to the speech-dispatcher-rs backend to always segfault:

```console
malloc@L:~/tts-rs$ cargo run --example hello_world
   Compiling speech-dispatcher-sys v0.5.2
   Compiling speech-dispatcher v0.7.0
   Compiling tts v0.18.3 (/home/malloc/tts-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.43s
     Running `target/debug/examples/hello_world`
Segmentation fault
```

**Comment by ndarilek** [comment]
Should be fixed in 0.19, which will be released shortly. Thanks for the report.
