### ISSUE TITLE
Implementing Debug trait and other common traits

### ISSUE THREAD

**Issue by saona-raimundo** [ndarilek/tts-rs#17]
Hi there! 

Thank you for the crate!

I wanted to ask if we could implement the `Debug` trait... and other [common traits](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits), as advised by the Rust API guidelines.

I am happy to do some PRs if you want to.

**Comment by ndarilek** [comment]
The challenge is that things need to work on multiple platforms, and 
IIRC `Debug` and others are challenging to make work universally.

Feel free to contribute PRs if you like, but note that any which fail to 
build on all platforms can't be accepted.

Thanks!

**Comment by saona-raimundo** [comment]
Thank you! 

I did not know how to test it on all platforms, should I install the toolchains and build the crate? I did not see any automatic test in Github.

**Comment by ndarilek** [comment]
There is the GitHub CI workflow that builds for all platforms. I've just 
approved the workflow run, so we'll see how it goes.

Thanks!

**Comment by saona-raimundo** [comment]
Thank you! I fixed there some tests :)
