### ISSUE TITLE
Strange behavior setting voices with WinRT

### ISSUE THREAD

**Issue by Bear-03** [ndarilek/tts-rs#29]
When I run this snippet, even though I changed the voice, Microsoft David is still being used when I call `Tts::speak`.
```rust
let mut tts = Tts::default().unwrap();
let voice_names: Vec<_> = tts
            .voices()
            .unwrap()
            .into_iter()
            .map(|v| v.name())
            .collect();

println!("{:?}", voice_names);

tts.set_voice(&tts.voices().unwrap()[1]).unwrap();
tts.speak("hello", false).unwrap();
```
stdout:
```
["Microsoft David", "Microsoft Zira", "Microsoft Mark"]
```
Looking at the output of the program, "hello" should be said by Zira, not David. Interestingly enough, everything works fine with the following change:
```rust
// ... (same as before)

tts.speak("", false).unwrap(); // Fixes voices
tts.set_voice(&tts.voices().unwrap()[1]).unwrap();
tts.speak("hello", false).unwrap(); // Now this will be said by Zira
```
This makes me think `Tts::speak` performs some kind of initialization that allows changing the voices afterwards.

**Comment by ndarilek** [comment]
Give main a shot, and if it works for you then I'll make a new release. Sorry about that--there were indeed two paths and I hadn't set the voice on one of them. Thanks for the report!

**Comment by Bear-03** [comment]
Setting the voice works in the main branch, but getting it doesn't. If I call `Tts::voice`, without calling `Tts::speak` first, the old voice will be returned.

Maybe it would make more sense for `Tts::voice` to return `self.voice` instead of calling `self.synth.Voice()`, although I think calling `self.synth.SetVoice()` when `Tts::set_voice` is called would be better, as it avoids having to store the `Voice` in the struct.

**Comment by ndarilek** [comment]
Ah, you're right, it should just return `self.voice`. I implemented 
voice support into so many speech APIs at once that I didn't have time 
to think through each one carefully. Feel free to submit a PR, otherwise 
I'll get to it on Monday and push out a new release.

Thanks for testing!

**Comment by Bear-03** [comment]
I'll open a PR, it's a quick fix :P. Is there any technical reason why you chose to store the voice, rate, pitch and volume in the struct itself? As I see it, calling the methods in `SpeechSynthesizer` directly would reduce the complexity of the struct, and also prevent errors like this one.

**Comment by ndarilek** [comment]
There's no other way I know of to indicate which parameters a given 
utterance should speak with. If you don't store the properties and set 
them at the time you speak something, you'll run into situations where 
you speak a thing, change synth properties, queue up something else, and 
the results are inconsistent. Feel free to try another way in case I'm 
wrong, but it seems like most TTS APIs handle these parameters on an 
utterance-by-utterance basis.

**Comment by Bear-03** [comment]
Isn't it possible to call all of these in their respective `set` methods, instead of doing it in every `Tts::speak` call?
```rs
self.synth.Options()?.SetSpeakingRate(self.rate.into())?;
self.synth.Options()?.SetAudioPitch(self.pitch.into())?;
self.synth.Options()?.SetAudioVolume(self.volume.into())?;
self.synth.SetVoice(&self.voice)?;
```
You would still have to store the voice because there is no way to convert from `Voice` to `VoiceInformation` in `set_voice`, but could remove `self.pitch`, `self.rate` and `self.volume` because you could pass the properties directly to the synth like this:
```rs
fn get_volume(&self) -> std::result::Result<f32, Error> {
    Ok(self.synth.Options()?.AudioVolume()? as f32)
}

fn set_volume(&mut self, volume: f32) -> std::result::Result<(), Error> {
    self.synth.Options()?.SetAudioVolume(volume as f64)?;
    Ok(())
}
```

**Comment by ndarilek** [comment]
It sounds like you have a good idea for a path forward. Why not give 
that a shot and see if it runs all the examples correctly? If it does, 
and if it holds up in my production use, I'll merge it.

Elaborating more on my previous comment, it behaved inconsistently. 
Sometimes rate/voice changes didn't take effect in time for utterances 
to queue up. It's possible that went away in an unrelated fix and it 
isn't needed anymore, but if it isn't broken for me then I personally 
don't have the time to fix it. :) Again, if you have the time to make 
your changes, and if they work, I'm happy to accept them.

**Comment by Bear-03** [comment]
Great! I'll give it a go :D
