### ISSUE TITLE
Add support for SAPI on Windows through COM

### ISSUE THREAD

**Issue by Keithcat1** [ndarilek/tts-rs#3]
Hi,
Can you add SAPI via COM on Windows?
The WinRT bindings are only available on windows 10 I think. Also it can take quite a while to compile, as far as I can tell it generates literally 12 MB worth of bindings.

**Comment by ndarilek** [comment]
Wild, I thought I'd responded to this but I guess not.

I think I'll pass on SAPI support. 1. Windows 8/8.1 will be EOL in a couple years, meaning we'd essentially work hard to add another backend that gets pulled/deprecated anyway. 2. v0.15.0, released today, vastly speeds up compilation of the UWP backend. There is no longer a separate bindings crate.

I'd welcome PRs that add SAPI support, along with a commitment to maintain them. But I myself won't be adding them. Sorry.
