### ISSUE TITLE
Docs are failing and so is my build for Linux

### ISSUE THREAD

**Issue by lesleyrs** [ndarilek/tts-rs#42]
`cargo add tts --no-default-features --features speech_dispatcher_0_10` is required for me to get it to run on Debian/WSL.

I get the same error as on docs.rs but this fixes it for me.

It's annoying that you can't have both features without the error though, makes it impossible to distribute 1 executable that works regardless of version.

**Comment by ndarilek** [comment]
Thanks for the report. I may have fixed docs.rs builds in 0.25.4--I'll verify and close this when I do.

**Comment by lesleyrs** [comment]
Could you also remove default so that we can create 1 binary and just select the feature when running or installing? Because I don't think you can turn off default features with `--no-default-features` on the command line for dependencies.

This would be a little annoying for people that have 0_11 available but 0_10 might be more common? Not sure. https://github.com/ndarilek/tts-rs/blob/e6e1cd49bf22ccff78e5f0f3cffde885a2e8ce64/Cargo.toml#L18

**Comment by ndarilek** [comment]
docs.rs works for V0.25.5. Thanks for the report.
